### ISSUE TITLE
Weird message when I try to hibernate

### ISSUE THREAD

**Issue by vixalien** [arelange/gnome-shell-extension-hibernate-status#92] opened 2023-02-07 11:46 UTC
Weird message when I try to hibernate

![PXL_20230207_114524313.jpg](https://user-images.githubusercontent.com/37999241/217236555-0583fe63-fdb4-44dd-a859-d01e4c8bd902.jpg)

**Comment by p91paul** [comment] 2023-02-07 18:21
if your system fails to hibernate in a reasonable timeframe, the extension tells you something is wrong with your system. Please check the hibernation guide for your distribution to learn how to enable hibernation.
You can leave this bug open because the message formatting clearly went bad with some gnome shell update

**Comment by vixalien** [comment] 2023-02-08 10:24
Oh alright. I have my hibernation set up correctly, I think it's because I had a sleep inhibitting extension on (Caffeine or Keep Awake)

**Comment by slaclau** [comment] 2023-10-17 21:26
@p91paul does this still need to be open - how come you closed it then reopened?

**Comment by p91paul** [comment] 2023-10-18 17:10
The issue is with the dialog formatting (see screenshot above). I closed by mistake, I never checked with more recent gs version if this is actually fixed.

**Comment by slaclau** [comment] 2023-10-18 17:23
I think my recent merge should have fixed this then - I’ll double check then close.On 18 Oct 2023, at 18:10, Paolo Inaudi ***@***.***> wrote:﻿
The issue is with the dialog formatting (see screenshot above). I closed by mistake, I never checked with more recent gs version if this is actually fixed.

**Closed** 2023-11-05 22:04 UTC
Labels: bug
