### ISSUE TITLE
 No JS module 'prefs' found in search path

### ISSUE THREAD

**Issue by inverse** [arelange/gnome-shell-extension-hibernate-status#42] opened 2020-02-05 20:16 UTC
When trying to install from the gnome extensions website it displays error and I see this in `journalctl`

```
JS ERROR: Extension hibernate-status@dromi: ImportError: No JS module 'prefs' found in search path
                                          @/usr/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:13:7
                                          _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:343:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:22
                                          callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
                                          gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

OS: EndevourOS
Gnome: 3.34.3

**Comment by p91paul** [comment] 2020-10-11 17:32
Sorry for the long wait.
Looks like a duplicate of https://github.com/arelange/gnome-shell-extension-hibernate-status/issues/32

**Closed by p91paul** 2020-10-11 17:32 UTC
