### ISSUE TITLE
Error: Expected type object for Argument 'widget' but got type 'undefined'

### ISSUE THREAD

**Issue by rootinshik** [arelange/gnome-shell-extension-hibernate-status#56] opened 2020-07-05 17:44 UTC
Error: Expected type object for Argument 'widget' but got type 'undefined'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
OS: Arch Linux
Gnome version: 3.36.3

PS: `systemctl hibernate` works fine

**Comment by p91paul** [comment] 2020-07-06 23:52
duplicate of #53

**Closed** 2020-07-06 23:53 UTC
