### ISSUE TITLE
error updating extension

### ISSUE THREAD

**Issue by csylvain** [arelange/gnome-shell-extension-hibernate-status#61] opened 2020-10-11 22:14 UTC
received notification of new version. attempted update. result: ERROR displayed.
`The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`

**Comment by p91paul** [comment] 2020-10-12 07:14
Duplicate of #59.
Please uninstall and reinstall, and do not open preferences page, it's not implemented anyway.

**Comment by csylvain** [comment] 2020-10-12 20:15
have uninstalled extension, restarted browser, and then installed extension.
result: *immediate* error shown.

seriously: something has broken. (see attached screenshot)

**Comment by csylvain** [comment] 2020-10-12 20:27
![Hibernate-Extension-screenshot](https://user-images.githubusercontent.com/6507573/95787566-4de8e300-0cc9-11eb-8e9d-d75102878920.png)

**Comment by p91paul** [comment] 2020-10-12 21:01
can you collect logs during install?

**Comment by csylvain** [comment] 2020-10-12 23:31
which logs where? i'm not a browser extension coder.

**Comment by csylvain** [comment] 2020-10-13 23:09
upgrade successful with new version:  
[uninstall] 
ALT-F2
r
[install from Extensions]

the ALT-F2 r resets the gnome-shell

**Comment by nathan-weinberg** [comment] 2020-11-12 04:22
Encountered the same here as well

Running Fedora 32 with GNOME 3.36.7

```
Error: Expected type object for Argument 'widget' but got type 'undefined'

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by p91paul** [comment] 2020-11-12 08:09
see my last comment above.

**Comment by nathan-weinberg** [comment] 2020-11-13 03:09
Best way to do that?

**Comment by antoine-pous** [comment] 2020-11-30 10:59
@p91paul why don't you simply add a placeholder for the preferences panel? It will fix this issue properly. Actually i'm encountering the exact same issue, then the extension install is broken :/

**Comment by p91paul** [comment] 2020-11-30 23:48
I did it on the gnome shell 3.38 version, unfortunately you are stuck with an older one.

**Closed** 2020-11-30 23:48 UTC
