### ISSUE TITLE
Stopped working after updating to Ubuntu 20.04 (Gnome 3.36.1)

### ISSUE THREAD

**Issue by armujahid** [arelange/gnome-shell-extension-hibernate-status#45] opened 2020-04-27 16:30 UTC
**System details:**
    OS: Ubuntu 20.04
    Kernel: 5.4.0-26-generic
    Gnome shell version: 3.36.1

**Technical details:**
The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by armujahid** [comment] 2020-04-27 16:35
I just saw this note in readme. 
https://github.com/arelange/gnome-shell-extension-hibernate-status#gnome-shell-336
Thanks for developing and maintaining this extension :+1:   I hope that new extension will be created by someone soon.

**Comment by p91paul** [comment] 2020-05-03 22:14
Duplicate of https://github.com/arelange/gnome-shell-extension-hibernate-status/issues/44
Actually, there's an open pull request to fix this, so some hope is restored!

**Closed by p91paul** 2020-05-03 22:14 UTC
