### ISSUE TITLE
Undefined action menu

### ISSUE THREAD

**Issue by mokilcde** [arelange/gnome-shell-extension-hibernate-status#33] opened 2019-08-15 07:52 UTC
Hi!

I got the following message after updating to Gnome Shell version 3.33.90:
gnome-shell[2532]: JS WARNING: [/srv/home/michael/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js 187]: reference to undefined property "_actionsItem"
gnome-shell[2532]: Extension "hibernate-status@dromi" had error: TypeError: this.systemMenu._actionsItem is undefined

CU
  Michael

**Comment by p91paul** [comment] 2019-08-24 11:51
@davidbailey00 please confirm you are going to take care of this, since you are the maintainer on e.g.o...

**Comment by p91paul** [comment] 2019-11-10 10:05
duplicate of #34, which is now fixed in master.

**Closed by p91paul** 2019-11-10 10:05 UTC
