### ISSUE TITLE
Can't enable extension on GNOME 45

### ISSUE THREAD

**Issue by jugendhacker** [arelange/gnome-shell-extension-hibernate-status#110] opened 2023-10-21 15:16 UTC
The extensions application does not let me enable it on GNOME 45, because of `this.systemMenu is undefined`

Possibly related to #106

**Comment by asfernandes** [comment] 2023-10-22 12:23
It also still shows as incompatible for me in https://extensions.gnome.org/extension/755/hibernate-status-button/
Using Ubuntu 23.10 here.

**Comment by p91paul** [comment] 2023-10-22 12:30
Duplicate of #109

**Closed by p91paul** 2023-10-22 12:30 UTC

**Comment by jugendhacker** [comment] 2023-10-22 12:50
@p91paul IMHO this is not a duplicate of #109, as this issue here is about a actual bug that prevents me from using the extension rather than it not being on extensions.gnome.org (which 109 seems to be about)

**Comment by p91paul** [comment] 2023-10-22 21:56
@jugendhacker how did you install? I just assumed it was from extensions.gnome.org, but if you installed manually the code from here (and the extension tool didn't force update you) then something is wrong and I will reopen. Please try disabling other extensions to rule out extensions incompatibilities, as I've seen the extension mostly working, at least to the point of showing the hibernate entries in the menu.

**Comment by lobothiago** [comment] 2023-10-28 19:01
I'm getting the same error @jugendhacker mentioned when he opened this issue. Installed manually to GNOME 45.

![image](https://github.com/arelange/gnome-shell-extension-hibernate-status/assets/8550957/af338a22-516c-46c2-9e62-e5a535ffde95)

**Comment by lobothiago** [comment] 2023-10-28 20:09
I was able to make this work locally by delaying the initialization of the extension until `Main.panel.statusArea.quickSettings._system` becomes available. This explains why the issue happens in the first place: https://discourse.gnome.org/t/main-panel-statusarea-quicksettings-system-is-undefined/16827

I've never written gnome-shell extensions, so my fix might not follow some best practice - feel free to scratch it and do it appropriately :)
