### ISSUE TITLE
Probleme the shell 

### ISSUE THREAD

**Issue by carrabelloy** [arelange/gnome-shell-extension-hibernate-status#54] opened 2020-06-22 02:00 UTC
`The settings of extension hibernate-status@dromi had an error:
```
Error: Expected type object for Argument 'widget' but got type 'undefined'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:208:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`

**Comment by p91paul** [comment] 2020-06-24 21:55
duplicate of #53

**Closed** 2020-06-24 21:56 UTC
